### PR TITLE
o.c.alarm.diirt.datasource: fix the maven build

### PR DESCRIPTION
**Pull request by willrogers**
@shroffk these were the changes I had to make in order to make Maven build your branch successfully.

### CODE REVIEW

**Comment by shroffk** [comment]
Awesome, Thank you so much for doing this.

**Comment by shroffk** [comment]
Also, Do you guys have any use cases for this kind of datasource?

**Comment by willrogers** [comment]
We haven't used the alarm handler from CSS at all.  Ops have their own system, which I have never looked into.

Once CSS is deployed here in earnest, we might encourage them to use Beast so that it's better supported.

**Comment by shroffk** [comment]
Ah, ok then.

**Pull request merged**
